AppBundle\Entity\Question:
    type:  entity
    table: question
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        question_type:
            type: string
            lenght: 20
            options:
              default: "text"
        created_date:
            type: datetime
        modified_date:
            type: datetime
    manyToOne:
        user:
          targetEntity: AppBundle\Entity\User
          joinColumn:
            name: user_id
            referencedColumnName: id
    oneToMany:
        choices:
          targetEntity: AppBundle\Entity\Choice
          mappedBy: question
