AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        is_admin:
          type: boolean
          options:
            default: false
        first_name:
          type: string
          lenght: 50
        last_name:
          type: string
          lenght: 50